version: '3.7'
services:
    api:
        build: api
    analysis:
        build: analysis
    webapp: 
        build: webapp
    db:
        image: postgres:12.1
        volumes:
            - "db-data:/var/lib/postgresql/data"
        networks: 
            - back-tier

volumes:
    db-data: {}

networks:
    front-tier: {}
    back-tier: {}
