version: '3'
services:
  app:
    build: .
    command: 'puma -C config/puma.rb'
    stdin_open: true
    tty: true
    environment:
      - RAILS_ENV=development
    ports:
      - '80:3000'
    links:
      - postgres
    volumes:
      - .:/home/deploy/app

  postgres:
    image: postgres:9.6.2-alpine
    environment:
      - POSTGRES_PASSWORD=mysecretpassword
    ports:
      - '5432'
    volumes:
      - data:/var/lib/postgresql/data

volumes:
  data: